package com.trigyn.jws.formio.utils;

public final class Constants {

	private Constants() {

	}

	public static final String	FILE_BIN_HTML_CONTENT					= "<div class=\"dragpasteblock\">\r\n<div class=\"fileuploadmaster dropzone\"></div>\r\n<div class=\"jqFmioFileUploadImg\" style=\"display:flex; justify-content:flex-start;\">\r\n<img class=\"fileUploadIcon\"\r\n src=\"../webjars/1.0/images/fileupload.png\"\r\n style=\"cursor:pointer;\"\r\n height=\"50px\" />\r\n </div>\r\n </div>";

	public static final String	FILE_BIN_JS_CONTENT						= "$(function () {     \r\n  if (!window.__fileBinInitDone) {\r\n\t  window.__fileBinInitDone = true;\r\n\r\n\t  document.title = \"JQuiver\";\r\n\t  let contextPath = \"/hrsSIT\";\r\n\r\n\t  let dropZone = $(\".fileuploadmaster\").fileUpload({\r\n\t\tfileBinId: \"yourFileBinId\",\r\n\t\tfileAssociationId: $(\"#primaryKeyId\").val(),\r\n\t\tcreateFileBin: true,\r\n\t\trenderer: fileConfigRenderer,\r\n\t  });\r\n\t  dropZone.getSelectedFiles();\r\n\t  $(document).on('click', '.fileupload-actions.fa-trash', function () {\r\n\t\t  const fileUploadId = $(this).data('fileid');\t \r\n\t\t  if (fileUploadId) {\r\n\t\t\t dropZone.deleteFileById(fileUploadId);\r\n\t\t  }\r\n\t  });\r\n\t}\t\r\n\t\r\n});";

	public static final String	GRID_UTILS_JS_CONTENT					= "contextPath = \"yourContextPath\";\r\nlet primaryKeyDetails = {\"key\":\"\"};\r\nlet listingData  = [];\r\n$(function () {\r\n\t//Add all columns that needs to be displayed in the grid\r\n\tlet colM = [\r\n\t\t{ title: \"Column Name to be displayed\", width: 130, dataIndx: \"columnNameInQuery\", align: \"left\", halign: \"center\",\r\n\t\t\tfilter: { type: \"textbox\", condition: \"contain\", listeners: [\"change\"]}  },\r\n\t\t{ title: \"Action\", width: 50, minWidth: 115, dataIndx: \"action\", align: \"center\", halign: \"center\", render: manageRecord, sortable: false}\r\n\t];\r\n\r\n\tlet dataModel = {\r\n\t\turl: contextPath + \"/cf/pq-grid-data\"\t\t\r\n\t};\t\r\n\r\n\tlet grid = $(\"#yourGridId\").grid({\r\n\t  gridId: \"yourGridId\",\r\n\t  colModel: colM,\r\n\t  dataModel: dataModel\r\n\t});\r\n\r\n});\r\n\r\nfunction actionButtonRenderer(uiObject) {\r\n\tlistingData  [uiObject.rowIndx] = uiObject.rowData;\r\n\tlet rowIndx = uiObject.rowIndx;\r\n\treturn '<span id=\"'+rowIndx+'\" onclick=\"upsert('+ uiObject.rowIndx +')\" class= \"grid_action_icons\" title=\"Edit\"><i class=\"fa fa-pencil\"></i></span>'.toString();\r\n}\r\n\r\nfunction manageRecord(uiObject) {\r\n\tlistingData  [uiObject.rowIndx] = uiObject.rowData;\r\n\tlet rowIndx = uiObject.rowIndx;\r\n}\r\n\r\n//TODO :: Change the <formurl> URL \r\nfunction upsert(a_rowID){\r\n\tlet redirectURL = contextPath+jQuiverPropeties.getViewPath()+\"/<formurl>\";\r\n\tif(a_rowID != null && a_rowID != undefined && a_rowID >= 0){\r\n\t\t\tredirectURL += '?key=' + listingData[a_rowID][\"primary_key\"];\r\n\t}\r\n\tlocation.href = redirectURL;\r\n}\r\n\r\nfunction backToWelcomePage() {\r\n\tlocation.href = contextPath+\"/cf/home\";\r\n}";

	public static final String	TYPEAHEADAUTOCOMPLETE_UTILS_JS_CONTENT	= "contextPath = \"yourContextPath\";\r\nlet autocomplete;\r\nautocomplete = $(\"#autoCompId\").autocomplete({\r\n\tautocompleteId: \"autoCompId\",\r\n\tpageSize: 10,//Default page size is 10\r\n\tprefetch : false,\r\n\trender: function(item) {\r\n\t\tlet renderStr ='';      \r\n\t\tif(item.emptyMsg == undefined || item.emptyMsg === '')\r\n\t\t{\r\n\t\t\trenderStr = '<p>'+item.form_name+'</p>';\r\n\t\t}\r\n\t\telse\r\n\t\t{\r\n\t\t\trenderStr = item.emptyMsg;    \r\n\t\t}                                \r\n\t\treturn renderStr;\r\n\t},\t \r\n\tadditionalParamaters: {autoCompId: $('#autocompleteId').val()}, \r\n\trequestParameters: {},\r\n\textractText: function(item) {\r\n\t\treturn item.form_name;\r\n\t},\r\n\tselect: function(item) {\r\n\t\t$(\"#autoCompId\").blur();\r\n\t\t$(\"#autocompleteId\").val(item.form_io_id);\r\n\t\tautocomplete.setSelectedObject(item);\r\n\t},     \r\n\tresetAutocomplete: function(){ \r\n\t\t//This function will be executed onblur or when user click on clear text button\r\n\t\t//Code to reset dependent JavaScript variables, input fields etc.\r\n\t}\r\n\r\n});\r\n";

}