server:
  port: 8080
  shutdown: graceful
spring:
  profiles: ${profileName}
  resources:
    static-locations: classpath:/
  flyway:
    cleanDisabled: true
    enabled: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://${DB_URL}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true&serverTimezone=UTC&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    #comment url, username & password and uncomment below property if you want to use JDNI instead of direct connection
    #jndi-name: java:comp/env/jdbc/yourJNDI
logging:
  config: classpath:log4j2.xml
  level:
    root: info
    org:
      flywaydb: info
