server:
  port: 8080
  shutdown: graceful
#  address: 127.0.0.1
  servlet:
   session:
     persistent: false
#   context-path: /employee 
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1
  application:
    name: adc-demo
  flyway:
    cleanDisabled: true
    enabled: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/emp_test_12?createDatabaseIfNotExist=true&serverTimezone=UTC&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root
logging:
  level:
    root: info
    org:
      flywaydb: info
