ALTER TABLE `jq_module_listing` MODIFY COLUMN `last_updated_by` VARCHAR(50) NOT NULL DEFAULT 'admin@localhost.io';
ALTER TABLE `jq_resource_bundle` MODIFY COLUMN `created_by` VARCHAR(50) DEFAULT 'admin@localhost.io';
ALTER TABLE `jq_file_upload_config` MODIFY COLUMN `created_by` VARCHAR(500) DEFAULT 'admin@localhost.io';
ALTER TABLE `jq_additional_datasource` MODIFY COLUMN `created_by` VARCHAR(500) DEFAULT 'admin@localhost.io';

UPDATE `jq_autocomplete_details` SET `created_by`='admin@localhost.io' WHERE `created_by`='aar@jquiver.io';
UPDATE `jq_autocomplete_details` SET `created_by`='admin@localhost.io' WHERE `created_by`='admin@jquiver.io';
UPDATE `jq_autocomplete_details` SET `last_updated_by`='admin@localhost.io' WHERE `last_updated_by`='admin';
UPDATE `jq_dashboard` SET `created_by`='admin@localhost.io' WHERE `created_by`='admin@jquiver.io';
UPDATE `jq_dashboard_lookup_category` SET `updated_by`='admin@localhost.io' WHERE `updated_by`='admin@jquiver.io';
UPDATE `jq_dashlet` SET  `created_by`='admin@localhost.io' WHERE `created_by`='admin@jquiver.io';
UPDATE `jq_dashlet` SET `updated_by`='admin@localhost.io' WHERE `updated_by`='admin@jquiver.io';
UPDATE `jq_dynamic_form`  SET `created_by`='admin@localhost.io' WHERE `created_by`='admin@jquiver.io';
UPDATE `jq_dynamic_form`  SET `created_by`='admin@localhost.io' WHERE `created_by`='aar@jquiver.io';
UPDATE `jq_dynamic_form` SET `last_updated_by`='admin@localhost.io' WHERE `last_updated_by`='admin@jquiver.io';
UPDATE `jq_dynamic_rest_details` SET `created_by`='admin@localhost.io' WHERE `created_by`='aar@jquiver.io';
UPDATE `jq_dynamic_rest_details`  SET `created_by`='admin@localhost.io' WHERE `created_by`='admin@jquiver.io';
UPDATE `jq_dynamic_rest_details`  SET `created_by`='admin@localhost.io' WHERE `created_by`='admin@jquiver.io';
UPDATE `jq_entity_role_association`  SET `last_updated_by`='admin@localhost.io' WHERE `last_updated_by`='admin@jquiver.io';
UPDATE `jq_entity_role_association`  SET `last_updated_by`='admin@localhost.io' WHERE `last_updated_by`='aar@jquiver.io';
UPDATE `jq_file_upload` SET `updated_by`='admin@localhost.io' WHERE `updated_by`='admin@jquiver.io';
UPDATE `jq_file_upload_config` SET `created_by`='admin@localhost.io' WHERE `created_by`='aar@jquiver.io';
UPDATE `jq_file_upload_config` SET `created_by`='admin@localhost.io' WHERE `created_by`='admin@jquiver.io';
UPDATE `jq_file_upload_config` SET `created_by`='admin@localhost.io' WHERE `created_by`='admin@jquiver.io';
UPDATE `jq_file_upload_config` SET `last_updated_by`='admin@localhost.io' WHERE `last_updated_by`='admin@jquiver.io';
UPDATE `jq_grid_details` SET `created_by`='admin@localhost.io' WHERE `created_by`='aar@jquiver.io';
UPDATE `jq_grid_details`  SET `created_by`='admin@localhost.io' WHERE `created_by`='admin@jquiver.io';
UPDATE `jq_manual_entry` SET `last_updated_by`='admin@localhost.io' WHERE `last_updated_by`='admin@jquiver.io';
UPDATE `jq_property_master` SET `modified_by`='admin@localhost.io' WHERE `modified_by`='admin@jquiver.io';
UPDATE `jq_template_master`  SET `created_by`='admin@localhost.io' WHERE `created_by`='aar@jquiver.io';
UPDATE `jq_template_master`  SET `created_by`='admin@localhost.io' WHERE `created_by`='admin@jquiver.io';
UPDATE `jq_template_master`   SET `created_by`='admin@localhost.io' WHERE `created_by`='admin@jquiver.io';
UPDATE `jq_template_master`  SET `updated_by`='admin@localhost.io' WHERE `updated_by`='aar@jquiver.io';
UPDATE `jq_template_master`  SET `updated_by`='admin@localhost.io' WHERE `updated_by`='admin@jquiver.io';
UPDATE `jq_template_master`   SET `updated_by`='admin@localhost.io' WHERE `updated_by`='admin@jquiver.io';
UPDATE `jq_manual_entry` SET `last_updated_by` = 'admin@localhost.io' WHERE `last_updated_by` = 'admin@jquiver.io';
UPDATE `jq_resource_bundle` SET `created_by` = 'admin@localhost.io' WHERE `created_by` = 'admin@jquiver.io';
UPDATE `jq_module_listing` SET `last_updated_by` = 'admin@localhost.io' WHERE `last_updated_by` = 'admin@jquiver.io';

