server:
  port: 8080
  shutdown: graceful
spring:
  profiles: ${profileName}
  flyway:
    cleanDisabled: true
    enabled: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://${DB_URL}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true&serverTimezone=UTC&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
logging:
  level:
    root: info
    org:
      flywaydb: info
